var elements=[{
	"符号":"H",
	"名称_英文":"Hydrogen",
	"名称_简体中文":"氢",
	"名称_繁体中文":"氫",
	"相对原子质量":1.008
},{
	"符号":"He",
	"名称_英文":"Helium",
	"名称_简体中文":"氦",
	"名称_繁体中文":"氦",
	"相对原子质量":4.003
},{
	"符号":"Li",
	"名称_英文":"Lithium",
	"名称_简体中文":"锂",
	"名称_繁体中文":"鋰",
	"相对原子质量":6.941
},{
	"符号":"Be",
	"名称_英文":"Beryllium",
	"名称_简体中文":"铍",
	"名称_繁体中文":"鈹",
	"相对原子质量":9.012
},{
	"符号":"B",
	"名称_英文":"Boron",
	"名称_简体中文":"硼",
	"名称_繁体中文":"硼",
	"相对原子质量":10.811
},{
	"符号":"C",
	"名称_英文":"Carbon",
	"名称_简体中文":"碳",
	"名称_繁体中文":"碳",
	"相对原子质量":12.011
},{
	"符号":"N",
	"名称_英文":"Nitrogen",
	"名称_简体中文":"氮",
	"名称_繁体中文":"氮",
	"相对原子质量":14.007
},{
	"符号":"O",
	"名称_英文":"Oxygen",
	"名称_简体中文":"氧",
	"名称_繁体中文":"氧",
	"相对原子质量":15.999
},{
	"符号":"F",
	"名称_英文":"Fluorine",
	"名称_简体中文":"氟",
	"名称_繁体中文":"氟",
	"相对原子质量":18.998
},{
	"符号":"Ne",
	"名称_英文":"Neon",
	"名称_简体中文":"氖",
	"名称_繁体中文":"氖",
	"相对原子质量":20.180
},{
	"符号":"Na",
	"名称_英文":"Sodium",
	"名称_简体中文":"钠",
	"名称_繁体中文":"鈉",
	"相对原子质量":22.990
},{
	"符号":"Mg",
	"名称_英文":"Magnesium",
	"名称_简体中文":"镁",
	"名称_繁体中文":"鎂",
	"相对原子质量":24.305
},{
	"符号":"Al",
	"名称_英文":"Aluminum",
	"名称_简体中文":"铝",
	"名称_繁体中文":"鋁",
	"相对原子质量":26.982
},{
	"符号":"Si",
	"名称_英文":"Silicon",
	"名称_简体中文":"硅",
	"名称_繁体中文":"矽",
	"相对原子质量":28.086
},{
	"符号":"P",
	"名称_英文":"Phosphorus",
	"名称_简体中文":"磷",
	"名称_繁体中文":"磷",
	"相对原子质量":30.974
},{
	"符号":"S",
	"名称_英文":"Sulfur",
	"名称_简体中文":"硫",
	"名称_繁体中文":"硫",
	"相对原子质量":32.066
},{
	"符号":"Cl",
	"名称_英文":"Chlorine",
	"名称_简体中文":"氯",
	"名称_繁体中文":"氯",
	"相对原子质量":35.453
},{
	"符号":"Ar",
	"名称_英文":"Argon",
	"名称_简体中文":"氩",
	"名称_繁体中文":"氬",
	"相对原子质量":39.948
},{
	"符号":"K",
	"名称_英文":"Potassium",
	"名称_简体中文":"钾",
	"名称_繁体中文":"鉀",
	"相对原子质量":39.098
},{
	"符号":"Ca",
	"名称_英文":"Calcium",
	"名称_简体中文":"钙",
	"名称_繁体中文":"鈣",
	"相对原子质量":40.078
},{
	"符号":"Sc",
	"名称_英文":"Scandium",
	"名称_简体中文":"钪",
	"名称_繁体中文":"鈧",
	"相对原子质量":44.956
},{
	"符号":"Ti",
	"名称_英文":"Titanium",
	"名称_简体中文":"钛",
	"名称_繁体中文":"鈦",
	"相对原子质量":47.867
},{
	"符号":"V",
	"名称_英文":"Vanadium",
	"名称_简体中文":"钒",
	"名称_繁体中文":"釩",
	"相对原子质量":50.942
},{
	"符号":"Cr",
	"名称_英文":"Chromium",
	"名称_简体中文":"铬",
	"名称_繁体中文":"鉻",
	"相对原子质量":51.996
},{
	"符号":"Mn",
	"名称_英文":"Manganese",
	"名称_简体中文":"锰",
	"名称_繁体中文":"錳",
	"相对原子质量":54.938
},{
	"符号":"Fe",
	"名称_英文":"Iron",
	"名称_简体中文":"铁",
	"名称_繁体中文":"鐵",
	"相对原子质量":55.845
},{
	"符号":"Co",
	"名称_英文":"Cobalt",
	"名称_简体中文":"钴",
	"名称_繁体中文":"鈷",
	"相对原子质量":58.933
},{
	"符号":"Ni",
	"名称_英文":"Nickel",
	"名称_简体中文":"镍",
	"名称_繁体中文":"鎳",
	"相对原子质量":58.693
},{
	"符号":"Cu",
	"名称_英文":"Copper",
	"名称_简体中文":"铜",
	"名称_繁体中文":"銅",
	"相对原子质量":63.546
},{
	"符号":"Zn",
	"名称_英文":"Zinc",
	"名称_简体中文":"锌",
	"名称_繁体中文":"鋅",
	"相对原子质量":65.38
},{
	"符号":"Ga",
	"名称_英文":"Gallium",
	"名称_简体中文":"镓",
	"名称_繁体中文":"鎵",
	"相对原子质量":69.723
},{
	"符号":"Ge",
	"名称_英文":"Germanium",
	"名称_简体中文":"锗",
	"名称_繁体中文":"鍺",
	"相对原子质量":72.630
},{
	"符号":"As",
	"名称_英文":"Arsenic",
	"名称_简体中文":"砷",
	"名称_繁体中文":"砷",
	"相对原子质量":74.922
},{
	"符号":"Se",
	"名称_英文":"Selenium",
	"名称_简体中文":"硒",
	"名称_繁体中文":"硒",
	"相对原子质量":78.971
},{
	"符号":"Br",
	"名称_英文":"Bromine",
	"名称_简体中文":"溴",
	"名称_繁体中文":"溴",
	"相对原子质量":79.904
},{
	"符号":"Kr",
	"名称_英文":"Krypton",
	"名称_简体中文":"氪",
	"名称_繁体中文":"氪",
	"相对原子质量":83.798
},{
	"符号":"Rb",
	"名称_英文":"Rubidium",
	"名称_简体中文":"铷",
	"名称_繁体中文":"銣",
	"相对原子质量":85.468
},{
	"符号":"Sr",
	"名称_英文":"Strontium",
	"名称_简体中文":"锶",
	"名称_繁体中文":"鍶",
	"相对原子质量":87.62
},{
	"符号":"Y",
	"名称_英文":"Yttrium",
	"名称_简体中文":"钇",
	"名称_繁体中文":"釔",
	"相对原子质量":88.906
},{
	"符号":"Zr",
	"名称_英文":"Zirconium",
	"名称_简体中文":"锆",
	"名称_繁体中文":"鋯",
	"相对原子质量":91.224
},{
	"符号":"Nb",
	"名称_英文":"Niobium",
	"名称_简体中文":"铌",
	"名称_繁体中文":"鈮",
	"相对原子质量":92.906
},{
	"符号":"Mo",
	"名称_英文":"Molybdenum",
	"名称_简体中文":"钼",
	"名称_繁体中文":"鉬",
	"相对原子质量":95.95
},{
	"符号":"Tc",
	"名称_英文":"Technetium",
	"名称_简体中文":"锝",
	"名称_繁体中文":"鎝",
	"相对原子质量":98
},{
	"符号":"Ru",
	"名称_英文":"Ruthenium",
	"名称_简体中文":"钌",
	"名称_繁体中文":"釕",
	"相对原子质量":101.07
},{
	"符号":"Rh",
	"名称_英文":"Rhodium",
	"名称_简体中文":"铑",
	"名称_繁体中文":"銠",
	"相对原子质量":102.906
},{
	"符号":"Pd",
	"名称_英文":"Palladium",
	"名称_简体中文":"钯",
	"名称_繁体中文":"鈀",
	"相对原子质量":106.42
},{
	"符号":"Ag",
	"名称_英文":"Silver",
	"名称_简体中文":"银",
	"名称_繁体中文":"銀",
	"相对原子质量":107.868
},{
	"符号":"Cd",
	"名称_英文":"Cadmium",
	"名称_简体中文":"镉",
	"名称_繁体中文":"鎘",
	"相对原子质量":112.411
},{
	"符号":"In",
	"名称_英文":"Indium",
	"名称_简体中文":"铟",
	"名称_繁体中文":"銦",
	"相对原子质量":114.818
},{
	"符号":"Sn",
	"名称_英文":"Tin",
	"名称_简体中文":"锡",
	"名称_繁体中文":"錫",
	"相对原子质量":118.710
},{
	"符号":"Sb",
	"名称_英文":"Antimony",
	"名称_简体中文":"锑",
	"名称_繁体中文":"銻",
	"相对原子质量":121.760
},{
	"符号":"Te",
	"名称_英文":"Tellurium",
	"名称_简体中文":"碲",
	"名称_繁体中文":"碲",
	"相对原子质量":127.60
},{
	"符号":"I",
	"名称_英文":"Iodine",
	"名称_简体中文":"碘",
	"名称_繁体中文":"碘",
	"相对原子质量":126.904
},{
	"符号":"Xe",
	"名称_英文":"Xenon",
	"名称_简体中文":"氙",
	"名称_繁体中文":"氙",
	"相对原子质量":131.29
},{
	"符号":"Cs",
	"名称_英文":"Caesium",
	"名称_简体中文":"铯",
	"名称_繁体中文":"銫",
	"相对原子质量":132.905
},{
	"符号":"Ba",
	"名称_英文":"Barium",
	"名称_简体中文":"钡",
	"名称_繁体中文":"鋇",
	"相对原子质量":137.327
},{
	"符号":"La",
	"名称_英文":"Lanthanum",
	"名称_简体中文":"镧",
	"名称_繁体中文":"鑭",
	"相对原子质量":138.906
},{
	"符号":"Ce",
	"名称_英文":"Cerium",
	"名称_简体中文":"铈",
	"名称_繁体中文":"鈰",
	"相对原子质量":140.116
},{
	"符号":"Pr",
	"名称_英文":"Praseodymium",
	"名称_简体中文":"镨",
	"名称_繁体中文":"鐠",
	"相对原子质量":140.908
},{
	"符号":"Nd",
	"名称_英文":"Neodymium",
	"名称_简体中文":"钕",
	"名称_繁体中文":"釹",
	"相对原子质量":144.24
},{
	"符号":"Pm",
	"名称_英文":"Promethium",
	"名称_简体中文":"钷",
	"名称_繁体中文":"鉕",
	"相对原子质量":145
},{
	"符号":"Sm",
	"名称_英文":"Samarium",
	"名称_简体中文":"钐",
	"名称_繁体中文":"釤",
	"相对原子质量":150.36
},{
	"符号":"Eu",
	"名称_英文":"Europium",
	"名称_简体中文":"铕",
	"名称_繁体中文":"銪",
	"相对原子质量":151.964
},{
	"符号":"Gd",
	"名称_英文":"Gadolinium",
	"名称_简体中文":"钆",
	"名称_繁体中文":"釓",
	"相对原子质量":157.25
},{
	"符号":"Tb",
	"名称_英文":"Terbium",
	"名称_简体中文":"铽",
	"名称_繁体中文":"鋱",
	"相对原子质量":158.925
},{
	"符号":"Dy",
	"名称_英文":"Dysprosium",
	"名称_简体中文":"镝",
	"名称_繁体中文":"鏑",
	"相对原子质量":162.50
},{
	"符号":"Ho",
	"名称_英文":"Holmium",
	"名称_简体中文":"钬",
	"名称_繁体中文":"鈥",
	"相对原子质量":164.930
},{
	"符号":"Er",
	"名称_英文":"Erbium",
	"名称_简体中文":"铒",
	"名称_繁体中文":"鉺",
	"相对原子质量":167.26
},{
	"符号":"Tm",
	"名称_英文":"Thulium",
	"名称_简体中文":"铥",
	"名称_繁体中文":"銩",
	"相对原子质量":168.934
},{
	"符号":"Yb",
	"名称_英文":"Ytterbium",
	"名称_简体中文":"镱",
	"名称_繁体中文":"鐿",
	"相对原子质量":173.05
},{
	"符号":"Lu",
	"名称_英文":"Lutetium",
	"名称_简体中文":"镥",
	"名称_繁体中文":"鎦",
	"相对原子质量":174.967
},{
	"符号":"Hf",
	"名称_英文":"Hafnium",
	"名称_简体中文":"铪",
	"名称_繁体中文":"鉿",
	"相对原子质量":178.49
},{
	"符号":"Ta",
	"名称_英文":"Tantalum",
	"名称_简体中文":"钽",
	"名称_繁体中文":"鉭",
	"相对原子质量":180.948
},{
	"符号":"W",
	"名称_英文":"Tungsten",
	"名称_简体中文":"钨",
	"名称_繁体中文":"鎢",
	"相对原子质量":183.84
},{
	"符号":"Re",
	"名称_英文":"Rhenium",
	"名称_简体中文":"铼",
	"名称_繁体中文":"錸",
	"相对原子质量":186.207
},{
	"符号":"Os",
	"名称_英文":"Osmium",
	"名称_简体中文":"锇",
	"名称_繁体中文":"鋨",
	"相对原子质量":190.23
},{
	"符号":"Ir",
	"名称_英文":"Iridium",
	"名称_简体中文":"铱",
	"名称_繁体中文":"銥",
	"相对原子质量":192.217
},{
	"符号":"Pt",
	"名称_英文":"Platinum",
	"名称_简体中文":"铂",
	"名称_繁体中文":"鉑",
	"相对原子质量":195.078
},{
	"符号":"Au",
	"名称_英文":"Gold",
	"名称_简体中文":"金",
	"名称_繁体中文":"金",
	"相对原子质量":196.967
},{
	"符号":"Hg",
	"名称_英文":"Mercury",
	"名称_简体中文":"汞",
	"名称_繁体中文":"汞",
	"相对原子质量":200.59
},{
	"符号":"Tl",
	"名称_英文":"Thallium",
	"名称_简体中文":"铊",
	"名称_繁体中文":"鉈",
	"相对原子质量":204.383
},{
	"符号":"Pb",
	"名称_英文":"Lead",
	"名称_简体中文":"铅",
	"名称_繁体中文":"鉛",
	"相对原子质量":207.2
},{
	"符号":"Bi",
	"名称_英文":"Bismuth",
	"名称_简体中文":"铋",
	"名称_繁体中文":"鉍",
	"相对原子质量":208.980
},{
	"符号":"Po",
	"名称_英文":"Polonium",
	"名称_简体中文":"钋",
	"名称_繁体中文":"釙",
	"相对原子质量":209
},{
	"符号":"At",
	"名称_英文":"Astatine",
	"名称_简体中文":"砹",
	"名称_繁体中文":"砈",
	"相对原子质量":210
},{
	"符号":"Rn",
	"名称_英文":"Radon",
	"名称_简体中文":"氡",
	"名称_繁体中文":"氡",
	"相对原子质量":222
},{
	"符号":"Fr",
	"名称_英文":"Francium",
	"名称_简体中文":"钫",
	"名称_繁体中文":"鍅",
	"相对原子质量":223
},{
	"符号":"Ra",
	"名称_英文":"Radium",
	"名称_简体中文":"镭",
	"名称_繁体中文":"鐳",
	"相对原子质量":226
},{
	"符号":"Ac",
	"名称_英文":"Actinium",
	"名称_简体中文":"锕",
	"名称_繁体中文":"錒",
	"相对原子质量":227
},{
	"符号":"Th",
	"名称_英文":"Thorium",
	"名称_简体中文":"钍",
	"名称_繁体中文":"釷",
	"相对原子质量":232.038
},{
	"符号":"Pa",
	"名称_英文":"Protactinium",
	"名称_简体中文":"镤",
	"名称_繁体中文":"鏷",
	"相对原子质量":231.036
},{
	"符号":"U",
	"名称_英文":"Uranium",
	"名称_简体中文":"铀",
	"名称_繁体中文":"鈾",
	"相对原子质量":238.029
},{
	"符号":"Np",
	"名称_英文":"Neptunium",
	"名称_简体中文":"镎",
	"名称_繁体中文":"錼",
	"相对原子质量":237
},{
	"符号":"Pu",
	"名称_英文":"Plutonium",
	"名称_简体中文":"钚",
	"名称_繁体中文":"鈽",
	"相对原子质量":244
},{
	"符号":"Am",
	"名称_英文":"Americium",
	"名称_简体中文":"镅",
	"名称_繁体中文":"鋂",
	"相对原子质量":243
},{
	"符号":"Cm",
	"名称_英文":"Curium",
	"名称_简体中文":"锔",
	"名称_繁体中文":"鋦",
	"相对原子质量":247
},{
	"符号":"Bk",
	"名称_英文":"Berkelium",
	"名称_简体中文":"锫",
	"名称_繁体中文":"鉳",
	"相对原子质量":247
},{
	"符号":"Cf",
	"名称_英文":"Californium",
	"名称_简体中文":"锎",
	"名称_繁体中文":"鉲",
	"相对原子质量":251
},{
	"符号":"Es",
	"名称_英文":"Einsteinium",
	"名称_简体中文":"锿",
	"名称_繁体中文":"鑀",
	"相对原子质量":252
},{
	"符号":"Fm",
	"名称_英文":"Fermium",
	"名称_简体中文":"镄",
	"名称_繁体中文":"鐨",
	"相对原子质量":257
},{
	"符号":"Md",
	"名称_英文":"Mendelevium",
	"名称_简体中文":"钔",
	"名称_繁体中文":"鍆",
	"相对原子质量":258
},{
	"符号":"No",
	"名称_英文":"Nobelium",
	"名称_简体中文":"锘",
	"名称_繁体中文":"鍩",
	"相对原子质量":259
},{
	"符号":"Lr",
	"名称_英文":"Lawrencium",
	"名称_简体中文":"铹",
	"名称_繁体中文":"鐒",
	"相对原子质量":266
},{
	"符号":"Rf",
	"名称_英文":"Rutherfordium",
	"名称_简体中文":"𬬻",
	"名称_繁体中文":"鑪",
	"相对原子质量":267
},{
	"符号":"Db",
	"名称_英文":"Dubnium",
	"名称_简体中文":"𬭊",
	"名称_繁体中文":"𨧀",
	"相对原子质量":268
},{
	"符号":"Sg",
	"名称_英文":"Seaborgium",
	"名称_简体中文":"𬭳",
	"名称_繁体中文":"𨭎",
	"相对原子质量":269
},{
	"符号":"Bh",
	"名称_英文":"Bohrium",
	"名称_简体中文":"𬭛",
	"名称_繁体中文":"𨨏",
	"相对原子质量":270
},{
	"符号":"Hs",
	"名称_英文":"Hassium",
	"名称_简体中文":"𬭶",
	"名称_繁体中文":"𨭆",
	"相对原子质量":277
},{
	"符号":"Mt",
	"名称_英文":"Meitnerium",
	"名称_简体中文":"鿏",
	"名称_繁体中文":"䥑",
	"相对原子质量":278
},{
	"符号":"Ds",
	"名称_英文":"Darmstadtium",
	"名称_简体中文":"𫟼",
	"名称_繁体中文":"鐽",
	"相对原子质量":281
},{
	"符号":"Rg",
	"名称_英文":"Roentgenium",
	"名称_简体中文":"𬬭",
	"名称_繁体中文":"錀",
	"相对原子质量":282
},{
	"符号":"Cn",
	"名称_英文":"Copernicium",
	"名称_简体中文":"鎶",
	"名称_繁体中文":"鎶",
	"相对原子质量":285
},{
	"符号":"Nh",
	"名称_英文":"Nihonium",
	"名称_简体中文":"鉨",
	"名称_繁体中文":"鉨",
	"相对原子质量":286
},{
	"符号":"Fl",
	"名称_英文":"Flerovium",
	"名称_简体中文":"𫓧",
	"名称_繁体中文":"鈇",
	"相对原子质量":289
},{
	"符号":"Mc",
	"名称_英文":"Moscovium",
	"名称_简体中文":"镆",
	"名称_繁体中文":"鏌",
	"相对原子质量":290
},{
	"符号":"Lv",
	"名称_英文":"Livermorium",
	"名称_简体中文":"鉝",
	"名称_繁体中文":"鉝",
	"相对原子质量":293
},{
	"符号":"Ts",
	"名称_英文":"Tennessine",
	"名称_简体中文":"Tennessine",
	"名称_繁体中文":"Tennessine",
	"相对原子质量":294
},{
	"符号":"Og",
	"名称_英文":"Oganesson",
	"名称_简体中文":"Oganesson",
	"名称_繁体中文":"Oganesson",
	"相对原子质量":294
}]
function createList(ul){
	if(ul==null){
		var existingUl=document.getElementsByTag名称_英文("ul")
		if(existingUl.length>0){
			ul=existingUl[0]
		}else{
			var newUl=document.createElement("ul")
			document.body.appendChild(newUl)
			ul=newUl
		}
	}
	for(var i=0;i<elements.length;i++){
		var newLi=document.createElement("li")
		newLi.setAttribute("class","periodic-table")
		newLi.id=elements[i].名称_英文
		if(/zh-cn|zh-hans|zh-hans-cn/i.test(navigator.language)){
			newLi.innerText="原子序数："+(i+1)+"\n符号："+elements[i].符号+"\n名称："+elements[i].名称_简体中文+"\n相对原子质量："+elements[i].相对原子质量
		}else if(navigator.language.indexOf("zh")!=-1){
			newLi.innerText="原子序數："+(i+1)+"\n符號："+elements[i].符号+"\n名稱："+elements[i].名称_繁体中文+"\n相對原子質量："+elements[i].相对原子质量
		}else{
			newLi.innerText="Atomic number: "+(i+1)+"\n符号: "+elements[i].符号+"\n名称_英文: "+elements[i].名称_英文+"\nAtomic 相对原子质量: "+elements[i].相对原子质量
		}
		newLi.onclick=function(){
			try{
				elementClicked(getElement(this.id))
			}catch(e){
				console.log(e.message)
			}
		}
		ul.appendChild(newLi)
	}
}
function getElement(searchTerm){
	searchTerm=searchTerm.toLowerCase().trim()
	var mole=1
	for(var i=0;i<elements.length;i++){
		if(searchTerm.substr(0,4)=="mono"){
			mole=1
			searchTerm=searchTerm.replace("mono","")
		}else if(searchTerm.substr(0,2)=="di"){
			mole=2
			searchTerm=searchTerm.replace("di","")
		}else if(searchTerm.substr(0,3)=="tri"){
			mole=3
			searchTerm=searchTerm.replace("tri","")
		}else if(searchTerm.substr(0,5)=="tetra"){
			mole=4
			searchTerm=searchTerm.replace("tetra","")
		}else if(searchTerm.substr(0,5)=="penta"){
			mole=5
			searchTerm=searchTerm.replace("penta","")
		}else if(searchTerm.substr(0,4)=="hexa"){
			mole=6
			searchTerm=searchTerm.replace("hexa","")
		}else if(searchTerm.substr(0,5)=="hepta"){
			mole=7
			searchTerm=searchTerm.replace("hepta","")
		}else if(searchTerm.substr(0,4)=="octa"){
			mole=8
			searchTerm=searchTerm.replace("octa","")
		}else if(searchTerm.substr(0,4)=="nona"){
			mole=9
			searchTerm=searchTerm.replace("nona","")
		}else if(searchTerm.substr(0,4)=="deca"){
			mole=10
			searchTerm=searchTerm.replace("deca","")
		}else if(searchTerm.substr(0,6)=="undeca"){
			mole=11
			searchTerm=searchTerm.replace("undeca","")
		}else if(searchTerm.substr(0,6)=="dodeca"){
			mole=12
			searchTerm=searchTerm.replace("dodeca","")
		}else if(searchTerm.substr(0,1)=="一"){
			mole=1
			searchTerm=searchTerm.replace("一","")
		}else if(searchTerm.substr(0,1)=="二"){
			mole=2
			searchTerm=searchTerm.replace("二","")
		}else if(searchTerm.substr(0,1)=="三"){
			mole=3
			searchTerm=searchTerm.replace("三","")
		}else if(searchTerm.substr(0,1)=="四"){
			mole=4
			searchTerm=searchTerm.replace("四","")
		}else if(searchTerm.substr(0,1)=="五"){
			mole=5
			searchTerm=searchTerm.replace("五","")
		}else if(searchTerm.substr(0,1)=="六"){
			mole=6
			searchTerm=searchTerm.replace("六","")
		}else if(searchTerm.substr(0,1)=="七"){
			mole=7
			searchTerm=searchTerm.replace("七","")
		}else if(searchTerm.substr(0,1)=="八"){
			mole=8
			searchTerm=searchTerm.replace("八","")
		}else if(searchTerm.substr(0,1)=="九"){
			mole=9
			searchTerm=searchTerm.replace("九","")
		}else if(searchTerm.substr(0,1)=="十"){
			mole=10
			searchTerm=searchTerm.replace("十","")
		}
		var isNumber=new RegExp("[0-9]+")
		if(isNumber.test(searchTerm)){
			var num=parseInt(isNumber.exec(searchTerm)[0])
			if(num!=searchTerm){
				mole=num
				searchTerm=searchTerm.replace(mole,"")
			}
		}
		if(searchTerm.length<=2&&elements[i].符号.toLowerCase()==searchTerm||searchTerm.length>2&&elements[i].名称_英文.toLowerCase().indexOf(searchTerm)!=-1||elements[i].名称_简体中文==searchTerm||elements[i].名称_繁体中文==searchTerm||i+1==searchTerm||Math.round(elements[i].相对原子质量)==Math.round(searchTerm)){
			return{
				"相对原子质量":elements[i].相对原子质量*mole,
				"mole":mole,
				"名称_英文":elements[i].名称_英文,
				"名称_简体中文":elements[i].名称_简体中文,
				"名称_繁体中文":elements[i].名称_繁体中文,
				"number":i+1,
				"符号":elements[i].符号
			}
		}
	}
}
function getCompound(searchTerm){
	searchTerm=searchTerm.trim()
	var mole=1,record=new Array()
	if(searchTerm!=""){
		var isUpperCase=new RegExp("[A-Z]+")
		if(searchTerm.indexOf(" ")!=-1||isUpperCase.test(searchTerm)){
			var letters=searchTerm.split("")
			var tempRecord=new Array()
			searchTerm=""
			for(var i=0;i<letters.length;i++){
				searchTerm+=letters[i]
				var result=getElement(searchTerm.toLowerCase())
				if(result){
					tempRecord.push([{
						"符号":result.符号,
						"mole":result.mole,
						"相对原子质量":result.相对原子质量
					}])
				}
				if(letters[i]==" "||isUpperCase.test(letters[i+1])){
					record.push(tempRecord[tempRecord.length-1])
					tempRecord=new Array()
					mole=1
					searchTerm=""
				}
			}
			record.push(tempRecord[tempRecord.length-1])
		}else if(searchTerm.indexOf("化")!=-1){
			var characters=searchTerm.split("化")
			result=getElement(characters[1])
			if(result){
				record.push([{
					"符号":result.符号,
					"mole":result.mole,
					"相对原子质量":result.相对原子质量
				}])
			}
			mole=1
			result=getElement(characters[0])
			if(result){
				record.push([{
					"符号":result.符号,
					"mole":result.mole,
					"相对原子质量":result.相对原子质量
				}])
			}
		}else{
			return getElement(searchTerm)
		}
		var 相对原子质量=0,符号=""
		for(var i=0;i<record.length;i++){
			if(record[i]){
				符号+=record[i][0].符号
				if(record[i][0].mole>1){
					符号+=record[i][0].mole
				}
				相对原子质量+=record[i][0].相对原子质量
			}
		}
		return{
			"相对原子质量":相对原子质量,
			"符号":符号
		}
	}
}